# Generated by scripts/release/brew-formula.sh from dist-manifest.json (APIFAE-85).
# Do not edit by hand — the next release regenerates this file and overwrites
# any change made here.
class Apifae < Formula
  desc "Mock HTTP APIs locally and keep the mocks honest as the API changes"
  homepage "https://apifae.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://apifae.com/dl/0.6.0/apifae-0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "b057d8c3a91c3808b85790b5631192a598662f6f25646ffc574bad091011002e"
    end
    on_intel do
      url "https://apifae.com/dl/0.6.0/apifae-0.6.0-x86_64-apple-darwin.tar.gz"
      sha256 "315df23faed00a0552699b4570c9643f67b8054c8a761b593bdc9f3d05ea21ad"
    end
  end

  on_linux do
    on_arm do
      url "https://apifae.com/dl/0.6.0/apifae-0.6.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "c24995fab8300d963d1f6fdd252dd3057a9a092ed9710bbf7e45c0e3ab3a6fa7"
    end
    on_intel do
      url "https://apifae.com/dl/0.6.0/apifae-0.6.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "2e27ee2856ad3f4307b208a65ed0c8af6a86e678c1dd914676ce47ca27486719"
    end
  end

  def install
    bin.install "apifae"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/apifae --version")
  end
end
