# Generated by scripts/release/brew-formula.sh from dist-manifest.json (APIFAE-85).
# Do not edit by hand — the next release regenerates this file and overwrites
# any change made here.
class Apifae < Formula
  desc "Mock HTTP APIs locally and keep the mocks honest as the API changes"
  homepage "https://apifae.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://apifae.com/dl/0.3.0/apifae-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "82f016919fc3574097f4f02396bf38915c62940fcbce18e16fec46417975241e"
    end
    on_intel do
      url "https://apifae.com/dl/0.3.0/apifae-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "6a4f690651f20086ce6112b20f381f7a7f1ca66a01cea024c5ee7685aeb5d775"
    end
  end

  on_linux do
    on_arm do
      url "https://apifae.com/dl/0.3.0/apifae-0.3.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e65a4a0b24d750bd740c8af2e6a080809ce595514ff8c08b029a043d35e0d6c3"
    end
    on_intel do
      url "https://apifae.com/dl/0.3.0/apifae-0.3.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "ac8e1ea45c6757253ea0ae0d78316f090ccff527f725adfc6efaba701d2980bc"
    end
  end

  def install
    bin.install "apifae"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/apifae --version")
  end
end
