# Generated by scripts/release/brew-formula.sh from dist-manifest.json (APIFAE-85).
# Do not edit by hand — the next release regenerates this file and overwrites
# any change made here.
class Apifae < Formula
  desc "Mock HTTP APIs locally and keep the mocks honest as the API changes"
  homepage "https://apifae.com"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://apifae.com/dl/0.2.0/apifae-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "5d9865586341fdb7d6ae2a91587ef7be0ab438c46feade19ee37c66a8c8c4200"
    end
    on_intel do
      url "https://apifae.com/dl/0.2.0/apifae-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "4dc27b099776729671cc56b25452c341afb90f3056c04f8469208cbc6825dad6"
    end
  end

  on_linux do
    on_arm do
      url "https://apifae.com/dl/0.2.0/apifae-0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4f8368ae8b33c09804cbfdc37f60dd7a7f40e951079fc5e03eda35fd112a565f"
    end
    on_intel do
      url "https://apifae.com/dl/0.2.0/apifae-0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "9770b151b4fe410ab792ef042942048e65e7ffb38da5fa325c78adcf1574b802"
    end
  end

  def install
    bin.install "apifae"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/apifae --version")
  end
end
